# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='ifxf',
            new_name='isxf',
        ),
    ]
